"""add is_active and created_at to prompt_versions

Revision ID: 7200065078a3
Revises: add_status_to_runs
Create Date: 2026-02-04 19:51:35.969343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7200065078a3'
down_revision: Union[str, None] = 'add_status_to_runs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_versions', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_versions', 'is_active')
    # ### end Alembic commands ###
