"""add_ab_tests_table

Revision ID: a4d2ef240277
Revises: 15f54049780b
Create Date: 2026-09-29 23:21:27.677172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d2ef240277'
down_revision: Union[str, None] = '15f54049780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_tests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('version_a_id', sa.String(), nullable=False),
    sa.Column('version_b_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('answer_a', sa.Text(), nullable=False),
    sa.Column('answer_b', sa.Text(), nullable=False),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ab_tests')
    # ### end Alembic commands ###
